@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":SortPropertyCommand" as SortPropertyCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
participant ":SortedList<Property>" as SortedProperties MODEL_COLOR
end box

[-->SortPropertyCommand : execute(...)
activate SortPropertyCommand

SortPropertyCommand -> ModelManager : sortPropertyList(comparator)
activate ModelManager

ModelManager -> SortedProperties : setComparator(comparator)
activate SortedProperties

SortedProperties --> ModelManager
deactivate SortedProperties

ModelManager --> SortPropertyCommand
deactivate ModelManager

[<--SortPropertyCommand : new CommandResult(...)
deactivate SortPropertyCommand
@enduml
